title: The Daily Derja
params:
  author:
    name: "Jacob Shore"
    headline: نَسْمة شاميّة كُلّ يوم… مع أرشيف تونسي حلو
    bio: "Middle-aged, married, father of five. I write about Arabic, dialects, and daily life."
    links:
      - youtube: "https://www.youtube.com/@dewofyouryouth"
      - substack: "https://dailyderja.substack.com/"
      - github: "https://github.com/DewofyourYouth"
      - instagram: "https://www.instagram.com/yaakshore/"
      - discord: "https://discordapp.com/users/dew_of_your_youth"
      - link: "https://dewofyouryouth.com/"