main:
  - name: Blog
    url: /blog/
    weight: 1
  - name: Shami (Levantine)
    url: /dialects/shami/
    weight: 2
  - name: Tunisian
    url: /dialects/tunisian
    weight: 3
  - name: About
    url: /about/
    weight: 6
  - name: Dew of Your Youth
    url: https://jacob-shore.com
    weight: 7
footer:
  - name: Series
    url: /series/
    weight: 1
  - name: Categories
    url: /categories/
    weight: 2
  - name: Tags
    url: /tags/
    weight: 3