homepage:
  layout: hero
  title: The Daily Derja
  showRecent: true
  homepageImage: "/images/hero.jpg"
colorScheme: fire
logo: "/images/logo.png"
secondaryLogo: "/images/logo-dark.png"
description: "سلسلة تأملات يومية في الدارجة التونسية"
smartToc: true
list:
  showHero: true
  heroStyle: big
  showDate: true
  showAuthor: true
  showTags: true
  showCategories: true
  showCards: true
  showSummary: true
article:
  showHero: true
  showSummary: true
  showTaxonomies: true
  heroStyle: big
  showDate: true
  showAuthor: true
  showTags: true
  showCategories: true
  showReadingTime: true
  showComments: true
  showNextPrev: true
  showRelatedPosts: true
  relatedPostsCount: 3
